### ISSUE TITLE
Would be nice to add svgbob support to gnome-delineate app

### ISSUE THREAD

**Issue by PHHENS** [mbarkhau/asciigrid#4]
Dear Manuel,

Please take a look here :
[https://github.com/SeaDve/Delineate]()

At the moment it only supports graphviz, but the developer plan
to add mermaid support. It would be nice to add svgbob support to it
(make that app equivalent to asciigrid web app).
So it could be become a generic Diagram As Code App.

Thanks

**Comment by mbarkhau** [comment]
From what I can see in the screenshot, the gnome app apearse to use a declarative format. Do you know if they have any plans to support a grid based editor?

**Comment by PHHENS** [comment]
Dear Manuel,

I just posted your question to Dave, who develops Delineate, on its github :
https://github.com/SeaDve/Delineate/issues/5
I think, he will be pleased to help integrating svgbob support.

Thanks for your interest in a generic App As Code Editor.

**Comment by PHHENS** [comment]
Dear Manuel,
Since there is no feedback from Dave, please take a look 
to this GTK4 app which has a grid based text editor :
https://github.com/Nokse22/ascii-draw

Thanks

**Comment by mbarkhau** [comment]
I don't have the capacity for this. Please take it up with the ascii-draw project and point them to the svgbob repository, as that's where the binaries are that they'll be looking for.
