### ISSUE TITLE
Feature : support multiple version of bob2svg

### ISSUE THREAD

**Issue by PHHENS** [mbarkhau/asciigrid#5]
Dear Manuel,

It would be nice to allow bob2svg version selection on asciigrid editor.
In some cases, older versions might be more efficient (0.4.1, 0.5.5 ...).

Thanks for understanding this need.

**Comment by mbarkhau** [comment]
Hi @PHHENS,

the svgbob support is provided by [github.com/mbarkhau/markdown-svgbob](https://github.com/mbarkhau/markdown-svgbob), so I've opened an issue there: https://github.com/mbarkhau/markdown-svgbob/issues/5
